### ISSUE TITLE
New maintainers needed ?

### ISSUE THREAD

**Issue by ocramz** [vilu/purescript-browser-cookies#14]
Hi @vilu , this is a nice library and it would be a pity to let it bitrot.

A little more work is needed to make it standards-compliant, see #2 by @amcvega .

Would you be happy to open the package to new maintainers, or transfer ownership ? I'd be happy to help in case.

**Comment by vilu** [comment]
Sure! I’ve invited you to the repo for now. I’m not really using pure script at the moment and I’m happy to transfer ownership too if that helps.
